name: Actualizar Datos Inmobiliarios

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MI_TOKEN_PERSONAL }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: browser-actions/setup-chrome@latest

      - run: pip install pandas selenium webdriver-manager geopy

      - run: python scraper.py

      - run: |
          git config --global user.name 'Robot Inmobiliario'
          git config --global user.email 'bot@noreply.github.com'
          git add data.csv
          if git diff --staged --quiet; then
            echo "Sin cambios"
          else
            git commit -m "Auto-update data"
            git push
          fi
