name: Actualizar Datos Inmobiliarios

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MI_TOKEN_PERSONAL }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: browser-actions/setup-chrome@latest

      - run: pip install pandas selenium webdriver-manager geopy

      - run: python scraper.py

      - run: |
          # Solo intentamos guardar si el archivo existe
          if [ -f data.csv ]; then
            git config --global user.name 'Robot Inmobiliario'
            git config --global user.email 'bot@noreply.github.com'
            
            git add data.csv
            
            if git diff --staged --quiet; then
              echo "El archivo existe pero no tiene cambios nuevos."
            else
              git commit -m "Auto-update data"
              git push
            fi
          else
            echo "⚠️ ALERTA: El scraper no generó data.csv (probablemente encontró 0 propiedades)."
          fi
